[gdrive]
type = drive
scope = drive
token = {"access_token":"ya29.a0AQvPyIP6TfuUD9SHV2Spz79yZw1rEnP-E9PfDl5STX0FM3rVpKOZAOlphn5MOB19QrJvhFNTi4mW9ig0XpDRD4E7Y7SpcenptHkya0UXYv-bYlCHHjk-eVNkYsnHwliA-cCg4_ponXF8L5emSGXsITKmKJdM9TyT_L1K0vO22URR-PQiWBEPIiWqOySfJ1KIcnIsBQ8aCgYKAdsSARQSFQHGX2MiAZJWVZw-CBbyrm7_uX3IVg0206","token_type":"Bearer","refresh_token":"1//0g-wSBPp5jjluCgYIARAAGBASNwF-L9IrEqYgFmpD8jSYkFJa9194uAoIX8zF5F_XHmkSW49Y2PVdFfwwoNGDUIzUszIrf7ypEzc","expiry":"2026-05-19T08:50:15.8437753+05:30","expires_in":3599}

